### ISSUE TITLE
Remove uninstall and activation routine

### ISSUE THREAD

**Issue by r-a-y** [gavinr/embed-webmap#1]
Hi,

I think it is unnecessary to have an uninstall routine since your plugin is just a shortcode that doesn't add any options to the DB.

With the way you have it set up, during network-wide activation or uninstallation on a multisite install, it parses through every single WordPress site and does a `switch_to_blog()` call unnecessarily:
https://github.com/gavinr/embed-webmap/blob/master/src/public/class-embed-webmap.php#L115
https://github.com/gavinr/embed-webmap/blob/master/src/public/class-embed-webmap.php#L154
https://github.com/gavinr/embed-webmap/blob/master/src/uninstall.php#L19

On really large multisite installs, this can slow things down.

Let me know what you think.  If you want, I can do a pull request.

Thanks for the plugin!

**Comment by gavinr** [comment]
@r-a-y thanks for the report- I think you're probably right. I would really appreciate a PR from you here, and then i'll merge it and push it out to the WordPress plugins directory. Thanks!

**Comment by r-a-y** [comment]
@gavinr - Done!  See #2.

Can you hold off on the next release?  I have some other improvements to suggest in another PR.

**Comment by gavinr** [comment]
@r-a-y thanks! yes it'll probably take me a few days to get the time to test this.

**Comment by gavinr** [comment]
Version 2.0.2 released on wordpress.org - thanks for the PR! https://wordpress.org/plugins/embed-webmap/#description
